version: 2

updates:
    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: weekly
          day: monday
          time: '09:00'
          timezone: 'Asia/Tokyo'
      open-pull-requests-limit: 5
      labels:
          - enhancement
          - area:testing
      commit-message:
          prefix: chore
          include: scope
      ignore:
          - dependency-name: eslint
            update-types:
                - version-update:semver-major
      groups:
          npm-development:
              dependency-type: development
              patterns:
                  - '*'

    - package-ecosystem: github-actions
      directory: '/'
      schedule:
          interval: weekly
          day: monday
          time: '09:00'
          timezone: 'Asia/Tokyo'
      open-pull-requests-limit: 5
      labels:
          - enhancement
          - area:github
      commit-message:
          prefix: chore
          include: scope
